# Generated by Django 4.1.2 on 2022-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somethinglikespotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicid',
            name='artist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='musicid',
            name='musicfile',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='musicid',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
