# Generated by Django 4.1.2 on 2022-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tekst1', models.CharField(max_length=500)),
                ('tekst2', models.CharField(max_length=500)),
                ('obrazek1', models.FileField(upload_to='')),
            ],
        ),
    ]
